import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import localFont from "next/font/local";

const mango = localFont({
  src: "../../public/fonts/MangoDdobak-B.ttf",
  display: "swap",
  variable: "--font-mango",
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={mango.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
